### ISSUE TITLE
Page Setup and Flexbox pages are incomplete

### ISSUE THREAD

**Issue by SteveALee** [typestyle/typestyle.github.io#10]
http://typestyle.io/#/page and http://typestyle.io/#/flex content stops at the heading **Root**

have viewed in Firefox and Edge on Windows 10

**Comment by basarat** [comment]
Indeed. Cause : `root` is the id for the heading ... as well as where we render the react component. Will change the it of the react root :rose:

**Comment by SteveALee** [comment]
oops :)

Indecently, you can't use the heading ids as the fragment identifier in URLs due to the URL style :(

eg
http://typestyle.io/#/page#box-model

does not move to the **Box Model** section

**Comment by basarat** [comment]
> http://typestyle.io/#/page and http://typestyle.io/#/flex content stops at the heading Root

Fixed :rose: 

> Indecently, you can't use the heading ids as the fragment identifier in URLs due to the URL style :(

Yes. Instead use a `/` http://typestyle.io/#/page/box-model :rose:

That said many other libs do other tricks as well e.g. docute uses `?id` like https://formstate.github.io/#/?id=why . I just liked `/` for sub routing :heart:

**Comment by SteveALee** [comment]
Reading now! :)

**Comment by SteveALee** [comment]
PS ```<meta name="viewport" content="width=device-width, initial-scale=1.0">``` is usually recommended but not sure if scale is needed

eg ppk - http://www.quirksmode.org/mobile/metaviewport/

**Comment by basarat** [comment]
> but not sure if scale is needed

No one seems to be. Haven't found a reason for it. I copied the first one from https://css-tricks.com/snippets/html/responsive-meta-tag/ . I cannot add something that I do not know the reason for :rose:

**Comment by notoriousb1t** [comment]
initial-scale sets the starting zoom for mobile.  We probably should add it to prevent unintentional zooming and panning.

**Comment by SteveALee** [comment]
> https://css-tricks.com/snippets/html/responsive-meta-tag/

That's a useful site. The reasoning is partially explained there. Plus a sensible caveat too:

"Note: don't use a responsive meta tag if your website isn't specifically designed to be responsive and work well at that size, as it will make the experience worse."

But of course, "everyone" creates responsive sites these days :-/ heh
