### ISSUE TITLE
No longer free course on egghead.io

### ISSUE THREAD

**Issue by melwas** [typestyle/typestyle.github.io#18]
> We also have a free video course based on the same content as this guide if you prefer to watch instead of reading.

Unfortunately, as I see the course on the egghead.io is no longer free and needs PRO membership.

**Comment by basarat** [comment]
I've put a request to make it free similar to how the mobx course is free. Will update based on whatever they decide :rose:

**Comment by basarat** [comment]
It's free again 🌹
