### ISSUE TITLE
Embedding components into markdown docs

### ISSUE THREAD

**Issue by notoriousb1t** [typestyle/typestyle.github.io#2]
@basarat  I added a color grid with swatches of the named colors to the colors page.  I would also like to (at some point soon) show some examples of theming (think bootstrap colors) with large color swatches. 

http://typestyle.io/#/colors

What I am wondering is what is the best way to componentize these things in a way that I can call in the markdown files for docs?  Embedding styles in the markdown file isn't what I would call optimal.

**Comment by basarat** [comment]
> with large color swatches

Looks amazing! 

> What I am wondering is what is the best way to componentize these things

We can do custom rendering for when markdown hits certain tags e.g. : https://github.com/typestyle/typestyle.github.io/blob/ee3baf45aa9d05b533b48e6c5d6035c632a14cb5/src/components/markdown.tsx#L142-L143 

And here the code can be at least `ReactDOMServer.renderToString`. Returning dom `node` might also be possible but I haven't explored that.

PS: I am away till next monday at a conference :rose:

**Comment by basarat** [comment]
> We can do custom rendering for when markdown hits certain tags e.g.

Think that answered it :rose:
