### ISSUE TITLE
Example Playground No Longer Works

### ISSUE THREAD

**Issue by benpolinsky** [typestyle/typestyle.github.io#20]
https://typestyle.github.io/play/#src=style(%7Bcolor:%20'red'%7D)

Produces:

RENDER ERROR: Minified React error #46; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=46 for the full message or use the non-minified dev environment for full errors and additional helpful warnings

**Comment by notoriousb1t** [comment]
The playground works properly if you enter an element:

https://typestyle.github.io/play/#src=const%20redClass%20=%20style(%7Bcolor:%20'red'%7D);%0A%0A%3Cdiv%20className=%7BredClass%7D%3ESomething%3C/div%3E

**Comment by basarat** [comment]
The error message is unfortunate. We should wrap it with "Please read the playground docs https://typestyle.github.io/#/play  (DEBUG: Original message)" :rose:

**Comment by benpolinsky** [comment]
I was reading the docs. It was a direct example link that produced the error.

**Comment by benpolinsky** [comment]
Just checked and it is the theming example.

**Comment by basarat** [comment]
> Just checked and it is the theming example.

example fixed :rose:
