### ISSUE TITLE
Search Box doesn't work

### ISSUE THREAD

**Issue by jcpyun** [typestyle/typestyle.github.io#21]
Starting a week ago, search box stopped working on the front page

**Comment by jcpyun** [comment]
![screen shot 2018-04-11 at 2 47 10 pm](https://user-images.githubusercontent.com/8283878/38636801-48730ba2-3d97-11e8-8424-218b130ddc88.png)

**Comment by jcpyun** [comment]
it seems like you guys changed the input id from "doc-search-input" to "docsearch". I think that's why it's causing the bug

**Comment by basarat** [comment]
Check your browser extensions. Empty cache and hard reload. Or simply check again. It works for me right now: 

![image](https://user-images.githubusercontent.com/874898/38711088-ea6fefd6-3f06-11e8-9546-90bc688fd501.png)

Thanks for raising this though :rose:
