### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by aegatlin** [typestyle/typestyle.github.io#26]
This is a very exciting project. I'm excited to try it out.

I believe I found a typo in the docs website. This page, https://typestyle.github.io/#/flex. In the Example -> Vertical Examples, you replace `csstips` with `csx`, which I believe is incorrect.

You are maybe addressing this problem in #1  , but I can't tell, so wanted to flag it just in case.

**Comment by basarat** [comment]
> I believe I found a typo in the docs website. This page, https://typestyle.github.io/#/flex. In the Example -> Vertical Examples, you replace csstips with csx, which I believe is incorrect.

You are correct. Should be changed.

csstips + csx used to be one package a long time ago. csstips was rolled out because `csx` had a well defined purpose vs. `csstips` is *anything that is useful for beginners* :rose:
