### ISSUE TITLE
Color not working in playground examples

### ISSUE THREAD

**Issue by rpggio** [typestyle/typestyle.github.io#28]
The colors aren't working in the examples at https://typestyle.github.io/#/play.
Maybe shortcuts like `lightskyblue` have been removed from csx?
The TypeStyle sandbox does not give any hint that is the problem, but CodeSandbox does:
https://codesandbox.io/s/typestyle-csx-named-colors-olicg

**Comment by basarat** [comment]
They are not a part of csx. The playground docs e.g. https://typestyle.github.io/#/flex/arbitrary-layout show actual strings: 

```tsx
const bg = (color) => ({backgroundColor:color});

<div className={style(csstips.fillParent, csstips.vertical)}>
  <div className={style(csstips.content,csstips.height(50), bg('lightskyblue'))}>
    Header
  </div>
  <div className={style(csstips.flex, csstips.horizontal)}>
    <div className={style(csstips.content, csstips.width(100), bg('lightpink'))}>
      Sidebar
    </div>
    <div className={style(csstips.flex, bg('darkorange'))}>
      Body
    </div>
    <div className={style(csstips.content, csstips.width(100), bg('limegreen'))}>
      Sidebar
    </div>
  </div>
  <div className={style(csstips.content,csstips.height(50), bg('lightskyblue'))}>
    Footer
  </div>
</div>
```

Perhaps you found some docs that are invalid. If you share a link to them we can fix them :+1: Closing for now :rose:
